<a href="https://colab.research.google.com/github/VIKGO123/Network-Prediction/blob/master/ML_HACK.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from fastai.tabular import *

In [0]:
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).

In [0]:
data_dir = 'gdrive/My Drive/ml_hack'
# train = data_dir + '/train'
# valid_dir = data_dir + '/valid'
path=data_dir

In [0]:
train=data_dir+'/train.csv'
test=data_dir+'/test.csv'
user_features=data_dir+'/user_features.csv'

In [0]:
# path = untar_data(URLs.ADULT_SAMPLE)
df = pd.read_csv("gdrive/My Drive/ml_hack/mod_train.csv")

In [0]:
len(df)//2

200000

In [0]:
features=pd.read_csv(user_features)

In [0]:
features1=features.rename(columns={'node_id': 'node1_id'})

In [0]:
features2=features.rename(columns={'node_id': 'node2_id'})

In [0]:
import pandas as pd
import numpy as np

In [0]:
df1=df1.merge(features1,on="node1_id")

In [0]:
df1

,node1_id,node2_id,is_chat,f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,f11,f12,f13
0,8446602,6636127,0,22,0,0,24,0,0,24,0,0,26,0,0,15
1,1430102,7433949,0,0,0,0,0,0,0,0,0,0,0,0,0,7
2,1430102,4657876,0,0,0,0,0,0,0,0,0,0,0,0,0,7
3,1430102,6734841,0,0,0,0,0,0,0,0,0,0,0,0,0,7
4,1430102,5931925,0,0,0,0,0,0,0,0,0,0,0,0,0,7
5,2803017,8372333,0,9,2,0,14,7,1,14,7,1,14,7,1,15
6,4529348,894645,0,11,11,10,11,10,9,10,9,8,7,6,6,7
7,5096572,4211638,0,31,31,31,31,31,31,31,31,31,31,31,30,7
8,5096572,7337120,0,31,31,31,31,31,31,31,31,31,31,31,30,7
9,8325853,1305287,0,9,3,2,9,3,2,7,2,1,0,0,0,15
10,8325853,8076407,0,9,3,2,9,3,2,7,2,1,0,0,0,15
11,7218175,120961,0,0,0,0,5,2,0,11,2,0,18,3,0,15
12,7159649,7791327,1,0,0,0,2,2,0,8,7,2,15,13,6,10
13,4481049,7514725,0,31,6,0,31,5,0,31,7,0,31,7,1,15
14,2232007,4102278,0,31,31,31,31,31,31,31,31,31,31,31,31,15
15,5959148,750479,0,1,1,0,0,0,0,0,0,0,0,0,0,15
16,5959148,33262,0,1,1,0,0,0,0,0,0,0,0,0,0,15
17,321786,2806279,0,0,0,0,0,0,0,0,0,0,0,0,0,10
18,4220897,7257701,0,1,1,0,1,1,0,0,0,0,0,0,0,15
19,6696379,6883782,0,30,30,30,30,30,30,30,30,30,30,30,30,7
20,6696379,2591198,0,30,30,30,30,30,30,30,30,30,30,30,30,7
21,3233784,5549279,0,31,31,31,31,31,31,31,31,31,31,31,31,7
22,1143595,3096748,0,0,0,0,0,0,0,0,0,0,5,1,0,15
23,2762740,609777,0,30,3,0,31,3,0,31,5,0,31,9,0,15
24,8308507,4485604,0,31,2,0,28,5,0,22,5,0,15,4,0,4
25,2489784,3066726,0,31,1,0,31,2,0,31,4,0,31,3,0,15
26,4771042,998845,1,31,0,0,31,2,0,31,4,0,31,4,0,8
27,380641,757768,0,31,28,1,31,28,1,31,30,1,31,30,1,15
28,3728724,3302160,0,31,4,0,31,3,0,31,2,0,31,4,0,15
29,3728724,340950,0,31,4,0,31,3,0,31,2,0,31,4,0,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
399970,8361739,6077254,0,28,1,0,31,1,0,31,2,0,31,2,0,7
399971,7314542,3980616,0,0,0,0,2,1,0,2,1,0,2,1,0,15
399972,7207707,7444197,0,31,4,0,26,6,1,25,5,1,20,5,1,15
399973,5453633,2792356,0,0,0,0,0,0,0,0,0,0,5,0,0,15
399974,3703535,7353409,0,0,0,0,0,0,0,0,0,0,0,0,0,15
399975,8137947,8308676,1,31,30,27,31,30,27,31,30,27,31,30,27,15
399976,890724,1927590,0,31,5,0,31,5,0,31,4,0,31,2,0,15
399977,6519372,3976056,0,31,8,3,26,8,5,20,8,5,13,8,5,11
399978,479532,8836689,0,31,6,0,25,7,1,19,6,1,12,5,1,15
399979,892628,5230811,0,31,19,5,31,19,5,31,23,4,31,22,4,8
399980,5900077,5539794,0,31,4,0,31,3,0,31,3,0,31,1,0,15
399981,5558748,4666576,0,30,24,7,31,27,9,31,29,11,31,30,17,7
399982,313884,5633479,0,31,31,27,31,31,29,31,31,28,31,31,28,15
399983,4461270,1342132,0,31,10,0,31,9,0,31,7,0,31,7,0,15
399984,4455712,3246665,0,0,0,0,6,4,2,12,7,2,19,8,3,15
399985,2143861,3241362,0,0,0,0,0,0,0,1,1,0,5,2,0,4
399986,4861388,1578849,0,31,31,30,31,31,31,31,31,31,31,31,31,7
399987,2149336,23702,0,0,0,0,0,0,0,0,0,0,0,0,0,15
399988,2445812,904017,0,29,29,2,22,22,0,16,16,0,9,9,0,7
399989,767547,3852665,0,0,0,0,0,0,0,0,0,0,1,1,0,15
399990,1130475,4740547,0,31,12,4,31,14,4,31,13,3,31,9,0,4
399991,6624618,926114,0,0,0,0,0,0,0,0,0,0,0,0,0,15
399992,8459127,6552044,0,31,16,3,31,17,4,31,23,7,31,23,4,15
399993,4981707,2978709,0,31,5,0,31,2,0,31,2,0,31,3,0,15
399994,4957166,5501945,0,0,0,0,0,0,0,0,0,0,0,0,0,15
399995,379309,7518757,0,31,31,31,31,31,30,31,31,30,31,31,30,7
399996,8109347,1149669,0,0,0,0,3,0,0,9,0,0,16,5,0,7
399997,4439235,4442813,0,31,3,0,31,5,1,31,4,1,31,5,2,8
399998,8364129,7322004,0,31,4,0,31,3,0,31,3,0,31,4,0,15
399999,1902722,8625316,0,0,0,0,0,0,0,0,0,0,0,0,0,7

In [0]:
df1=df1.merge(features2,on="node2_id")

In [0]:
df1

,node1_id,node2_id,is_chat,f1_x,f2_x,f3_x,f4_x,f5_x,f6_x,f7_x,...,f4_y,f5_y,f6_y,f7_y,f8_y,f9_y,f10_y,f11_y,f12_y,f13_y
0,8446602,6636127,0,22,0,0,24,0,0,24,...,15,11,5,19,12,5,16,10,4,10
1,1430102,7433949,0,0,0,0,0,0,0,0,...,16,13,6,20,16,7,25,21,6,15
2,1430102,4657876,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,2,2,0,15
3,1430102,6734841,0,0,0,0,0,0,0,0,...,10,10,9,5,5,4,5,5,4,10
4,1430102,5931925,0,0,0,0,0,0,0,0,...,31,31,31,31,31,31,31,31,31,7
5,2803017,8372333,0,9,2,0,14,7,1,14,...,1,1,0,1,1,0,0,0,0,8
6,4529348,894645,0,11,11,10,11,10,9,10,...,1,1,1,1,1,1,1,1,1,15
7,5096572,4211638,0,31,31,31,31,31,31,31,...,7,1,0,9,1,0,16,1,0,7
8,5096572,7337120,0,31,31,31,31,31,31,31,...,0,0,0,0,0,0,0,0,0,15
9,8325853,1305287,0,9,3,2,9,3,2,7,...,0,0,0,4,2,0,8,6,0,15
10,8325853,8076407,0,9,3,2,9,3,2,7,...,8,0,0,12,3,0,12,3,0,15
11,7218175,120961,0,0,0,0,5,2,0,11,...,26,2,1,28,0,0,28,0,0,15
12,7159649,7791327,1,0,0,0,2,2,0,8,...,31,25,12,31,27,18,31,29,24,11
13,4481049,7514725,0,31,6,0,31,5,0,31,...,31,26,4,31,27,5,31,29,6,7
14,2232007,4102278,0,31,31,31,31,31,31,31,...,31,4,0,31,2,0,31,2,0,7
15,5959148,750479,0,1,1,0,0,0,0,0,...,31,0,0,31,0,0,31,0,0,5
16,5959148,33262,0,1,1,0,0,0,0,0,...,23,23,0,22,21,0,22,21,0,7
17,321786,2806279,0,0,0,0,0,0,0,0,...,31,28,28,31,29,29,31,31,31,15
18,4220897,7257701,0,1,1,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,7
19,6696379,6883782,0,30,30,30,30,30,30,30,...,9,9,8,11,11,7,10,10,6,7
20,6696379,2591198,0,30,30,30,30,30,30,30,...,31,11,8,31,17,14,31,16,14,4
21,3233784,5549279,0,31,31,31,31,31,31,31,...,31,6,0,31,8,0,31,9,0,15
22,1143595,3096748,0,0,0,0,0,0,0,0,...,29,1,0,29,3,0,29,4,0,15
23,2762740,609777,0,30,3,0,31,3,0,31,...,31,28,28,31,29,29,31,31,31,15
24,8308507,4485604,0,31,2,0,28,5,0,22,...,31,1,0,31,1,0,31,1,0,7
25,2489784,3066726,0,31,1,0,31,2,0,31,...,31,23,4,31,27,4,31,25,3,10
26,4771042,998845,1,31,0,0,31,2,0,31,...,31,10,0,31,10,0,31,10,2,8
27,380641,757768,0,31,28,1,31,28,1,31,...,9,4,1,9,4,1,9,4,1,15
28,3728724,3302160,0,31,4,0,31,3,0,31,...,31,11,0,31,11,0,31,9,0,6
29,3728724,340950,0,31,4,0,31,3,0,31,...,31,31,28,31,31,29,31,31,30,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
399970,3978592,7193643,0,13,0,0,20,3,1,26,...,0,0,0,0,0,0,0,0,0,7
399971,5427131,918655,0,31,20,7,31,23,9,31,...,0,0,0,0,0,0,0,0,0,15
399972,2668848,6080932,0,25,17,1,31,21,1,31,...,31,28,27,31,30,29,31,25,23,7
399973,8361739,6077254,0,28,1,0,31,1,0,31,...,0,0,0,2,2,0,7,7,5,7
399974,7314542,3980616,0,0,0,0,2,1,0,2,...,31,28,23,31,28,25,31,27,24,15
399975,7207707,7444197,0,31,4,0,26,6,1,25,...,31,27,15,31,26,19,31,26,19,15
399976,3703535,7353409,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,15
399977,8137947,8308676,1,31,30,27,31,30,27,31,...,31,29,26,31,30,27,31,30,27,7
399978,890724,1927590,0,31,5,0,31,5,0,31,...,28,27,12,22,21,11,15,15,8,7
399979,6519372,3976056,0,31,8,3,26,8,5,20,...,31,2,0,31,1,0,31,1,0,7
399980,479532,8836689,0,31,6,0,25,7,1,19,...,31,2,0,31,2,0,31,2,0,15
399981,892628,5230811,0,31,19,5,31,19,5,31,...,5,3,1,0,0,0,0,0,0,15
399982,5900077,5539794,0,31,4,0,31,3,0,31,...,0,0,0,0,0,0,0,0,0,15
399983,5558748,4666576,0,30,24,7,31,27,9,31,...,9,9,7,7,7,5,11,11,4,7
399984,313884,5633479,0,31,31,27,31,31,29,31,...,0,0,0,0,0,0,0,0,0,15
399985,4461270,1342132,0,31,10,0,31,9,0,31,...,26,26,26,20,20,20,13,13,13,15
399986,4455712,3246665,0,0,0,0,6,4,2,12,...,1,1,0,1,1,0,1,1,0,15
399987,2143861,3241362,0,0,0,0,0,0,0,1,...,30,2,0,30,2,0,30,2,0,15
399988,4861388,1578849,0,31,31,30,31,31,31,31,...,0,0,0,0,0,0,1,1,0,15
399989,2149336,23702,0,0,0,0,0,0,0,0,...,22,19,18,17,14,13,18,17,17,8
399990,2445812,904017,0,29,29,2,22,22,0,16,...,4,4,0,4,4,0,3,3,1,5
399991,767547,3852665,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,15
399992,6624618,926114,0,0,0,0,0,0,0,0,...,31,2,0,31,3,0,31,3,0,15
399993,8459127,6552044,0,31,16,3,31,17,4,31,...,31,27,12,31,27,13,31,22,11,15
399994,4981707,2978709,0,31,5,0,31,2,0,31,...,9,6,3,3,2,2,0,0,0,1
399995,4957166,5501945,0,0,0,0,0,0,0,0,...,1,1,0,1,1,0,1,1,0,10
399996,379309,7518757,0,31,31,31,31,31,30,31,...,31,31,30,31,31,30,31,31,31,15
399997,4439235,4442813,0,31,3,0,31,5,1,31,...,0,0,0,0,0,0,0,0,0,15
399998,8364129,7322004,0,31,4,0,31,3,0,31,...,0,0,0,4,3,2,11,10,8,8
399999,1902722,8625316,0,0,0,0,0,0,0,0,...,31,31,30,31,30,29,31,30,28,15

In [0]:

df1=df1.drop(['node1_id', 'node2_id'], axis=1)

In [0]:
df1.to_csv(path+'/mod_train.csv', index=False)

In [0]:
train=pd.read_csv(path+'/mod_train.csv')
train

,is_chat,f1_x,f2_x,f3_x,f4_x,f5_x,f6_x,f7_x,f8_x,f9_x,...,f4_y,f5_y,f6_y,f7_y,f8_y,f9_y,f10_y,f11_y,f12_y,f13_y
0,0,22,0,0,24,0,0,24,0,0,...,15,11,5,19,12,5,16,10,4,10
1,0,0,0,0,0,0,0,0,0,0,...,16,13,6,20,16,7,25,21,6,15
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,2,2,0,15
3,0,0,0,0,0,0,0,0,0,0,...,10,10,9,5,5,4,5,5,4,10
4,0,0,0,0,0,0,0,0,0,0,...,31,31,31,31,31,31,31,31,31,7
5,0,9,2,0,14,7,1,14,7,1,...,1,1,0,1,1,0,0,0,0,8
6,0,11,11,10,11,10,9,10,9,8,...,1,1,1,1,1,1,1,1,1,15
7,0,31,31,31,31,31,31,31,31,31,...,7,1,0,9,1,0,16,1,0,7
8,0,31,31,31,31,31,31,31,31,31,...,0,0,0,0,0,0,0,0,0,15
9,0,9,3,2,9,3,2,7,2,1,...,0,0,0,4,2,0,8,6,0,15
10,0,9,3,2,9,3,2,7,2,1,...,8,0,0,12,3,0,12,3,0,15
11,0,0,0,0,5,2,0,11,2,0,...,26,2,1,28,0,0,28,0,0,15
12,1,0,0,0,2,2,0,8,7,2,...,31,25,12,31,27,18,31,29,24,11
13,0,31,6,0,31,5,0,31,7,0,...,31,26,4,31,27,5,31,29,6,7
14,0,31,31,31,31,31,31,31,31,31,...,31,4,0,31,2,0,31,2,0,7
15,0,1,1,0,0,0,0,0,0,0,...,31,0,0,31,0,0,31,0,0,5
16,0,1,1,0,0,0,0,0,0,0,...,23,23,0,22,21,0,22,21,0,7
17,0,0,0,0,0,0,0,0,0,0,...,31,28,28,31,29,29,31,31,31,15
18,0,1,1,0,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,7
19,0,30,30,30,30,30,30,30,30,30,...,9,9,8,11,11,7,10,10,6,7
20,0,30,30,30,30,30,30,30,30,30,...,31,11,8,31,17,14,31,16,14,4
21,0,31,31,31,31,31,31,31,31,31,...,31,6,0,31,8,0,31,9,0,15
22,0,0,0,0,0,0,0,0,0,0,...,29,1,0,29,3,0,29,4,0,15
23,0,30,3,0,31,3,0,31,5,0,...,31,28,28,31,29,29,31,31,31,15
24,0,31,2,0,28,5,0,22,5,0,...,31,1,0,31,1,0,31,1,0,7
25,0,31,1,0,31,2,0,31,4,0,...,31,23,4,31,27,4,31,25,3,10
26,1,31,0,0,31,2,0,31,4,0,...,31,10,0,31,10,0,31,10,2,8
27,0,31,28,1,31,28,1,31,30,1,...,9,4,1,9,4,1,9,4,1,15
28,0,31,4,0,31,3,0,31,2,0,...,31,11,0,31,11,0,31,9,0,6
29,0,31,4,0,31,3,0,31,2,0,...,31,31,28,31,31,29,31,31,30,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
399970,0,13,0,0,20,3,1,26,5,1,...,0,0,0,0,0,0,0,0,0,7
399971,0,31,20,7,31,23,9,31,28,12,...,0,0,0,0,0,0,0,0,0,15
399972,0,25,17,1,31,21,1,31,23,0,...,31,28,27,31,30,29,31,25,23,7
399973,0,28,1,0,31,1,0,31,2,0,...,0,0,0,2,2,0,7,7,5,7
399974,0,0,0,0,2,1,0,2,1,0,...,31,28,23,31,28,25,31,27,24,15
399975,0,31,4,0,26,6,1,25,5,1,...,31,27,15,31,26,19,31,26,19,15
399976,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,15
399977,1,31,30,27,31,30,27,31,30,27,...,31,29,26,31,30,27,31,30,27,7
399978,0,31,5,0,31,5,0,31,4,0,...,28,27,12,22,21,11,15,15,8,7
399979,0,31,8,3,26,8,5,20,8,5,...,31,2,0,31,1,0,31,1,0,7
399980,0,31,6,0,25,7,1,19,6,1,...,31,2,0,31,2,0,31,2,0,15
399981,0,31,19,5,31,19,5,31,23,4,...,5,3,1,0,0,0,0,0,0,15
399982,0,31,4,0,31,3,0,31,3,0,...,0,0,0,0,0,0,0,0,0,15
399983,0,30,24,7,31,27,9,31,29,11,...,9,9,7,7,7,5,11,11,4,7
399984,0,31,31,27,31,31,29,31,31,28,...,0,0,0,0,0,0,0,0,0,15
399985,0,31,10,0,31,9,0,31,7,0,...,26,26,26,20,20,20,13,13,13,15
399986,0,0,0,0,6,4,2,12,7,2,...,1,1,0,1,1,0,1,1,0,15
399987,0,0,0,0,0,0,0,1,1,0,...,30,2,0,30,2,0,30,2,0,15
399988,0,31,31,30,31,31,31,31,31,31,...,0,0,0,0,0,0,1,1,0,15
399989,0,0,0,0,0,0,0,0,0,0,...,22,19,18,17,14,13,18,17,17,8
399990,0,29,29,2,22,22,0,16,16,0,...,4,4,0,4,4,0,3,3,1,5
399991,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,15
399992,0,0,0,0,0,0,0,0,0,0,...,31,2,0,31,3,0,31,3,0,15
399993,0,31,16,3,31,17,4,31,23,7,...,31,27,12,31,27,13,31,22,11,15
399994,0,31,5,0,31,2,0,31,2,0,...,9,6,3,3,2,2,0,0,0,1
399995,0,0,0,0,0,0,0,0,0,0,...,1,1,0,1,1,0,1,1,0,10
399996,0,31,31,31,31,31,30,31,31,30,...,31,31,30,31,31,30,31,31,31,15
399997,0,31,3,0,31,5,1,31,4,1,...,0,0,0,0,0,0,0,0,0,15
399998,0,31,4,0,31,3,0,31,3,0,...,0,0,0,4,3,2,11,10,8,8
399999,0,0,0,0,0,0,0,0,0,0,...,31,31,30,31,30,29,31,30,28,15

In [0]:

test=pd.read_csv(test)

In [0]:
test

                id  node1_id  node2_id
0                1   7107094   8010772
1                2   7995251   2805801
2                3   2804693   8059549
3                4   4812472   7332370
4                5   5009985   4511909
5                6   2468596   4815398
6                7   6868911   3852905
7                8   7360625   4215365
8                9   1454579   3912969
9               10   2892778   8566574
10              11   6520213   6520213
11              12   8310965   8000031
12              13   2454265      4997
13              14   2972278    610943
14              15   8446768   5810858
15              16   5013805   1782512
16              17    922425   1126101
17              18   4459324   3412578
18              19   6394652    891946
19              20   8137653   6032127
20              21   5909695   7430767
21              22   5728552   4104707
22              23   4490189   3686319
23              24    950172   5735623
24              25    204579    797666
25              26   7315422   1134238
26              27   1886831   1923560
27              28    182325   5560928
28              29   7333055     22049
29              30   7101374   3963350
...            ...       ...       ...
11776938  11776939   8529471   8529471
11776939  11776940    393409   7672189
11776940  11776941   6791361   7513422
11776941  11776942   5352300   2640934
11776942  11776943   7300376   2376282
11776943  11776944   8549956   8549956
11776944  11776945    975922   1138069
11776945  11776946   8180660   5717487
11776946  11776947    952021   2453592
11776947  11776948   3105840   2106701
11776948  11776949   6359286   3356350
11776949  11776950   7227663   5498418
11776950  11776951   7524012   1749952
11776951  11776952   7454467    794670
11776952  11776953   1441180    983306
11776953  11776954    179166   5731147
11776954  11776955   1228581   8096353
11776955  11776956   8108009   2262522
11776956  11776957    381307   1997017
11776957  11776958    611063   3651130
11776958  11776959   7708206   8001666
11776959  11776960   3844411   3479775
11776960  11776961    242145   4614992
11776961  11776962   2087099   5578510
11776962  11776963   6621057   1606459
11776963  11776964   3712717   4103489
11776964  11776965   1869948   1225133
11776965  11776966     96987   3575681
11776966  11776967   2039953   1688520
11776967  11776968    641295   5575689

[11776968 rows x 3 columns]

In [0]:
test_new=pd.read_csv('gdrive/My Drive/ml_hack/mod_test.csv')

In [0]:
test_new=test_new.drop(['node1_id', 'node2_id'], axis=1)

In [0]:
test_new = test_new.sort_values(by='id')

In [0]:
test_new

,id,f1_x,f2_x,f3_x,f4_x,f5_x,f6_x,f7_x,f8_x,f9_x,...,f4_y,f5_y,f6_y,f7_y,f8_y,f9_y,f10_y,f11_y,f12_y,f13_y
0,1,31,6,1,31,6,1,31,8,1,...,31,24,3,31,25,3,31,26,4,15
10,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,7
58,3,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,15
119,4,14,5,1,12,4,1,6,3,1,...,0,0,0,1,1,0,1,1,0,15
182,5,31,31,31,31,31,31,31,31,30,...,0,0,0,1,1,1,1,1,1,7
232,6,31,4,2,31,5,2,31,4,2,...,31,21,0,31,23,0,31,24,0,15
348,7,31,2,0,31,2,0,31,2,0,...,30,5,0,24,5,0,17,3,0,4
367,8,19,1,0,19,3,0,24,3,1,...,26,0,0,26,0,0,24,0,0,15
410,9,12,10,9,17,12,10,21,13,11,...,0,0,0,0,0,0,0,0,0,7
420,10,0,0,0,4,1,0,10,1,0,...,31,31,31,31,31,31,31,31,31,15
422,11,20,20,10,19,19,10,22,22,14,...,19,19,10,22,22,14,24,24,16,8
444,12,31,4,0,31,5,0,31,6,1,...,20,3,0,26,6,0,31,5,0,7
505,13,31,28,22,31,28,20,31,28,18,...,0,0,0,0,0,0,7,4,1,7
652,14,13,13,13,6,6,6,0,0,0,...,0,0,0,0,0,0,0,0,0,15
654,15,31,0,0,31,1,0,31,1,0,...,31,13,8,31,10,6,31,14,9,7
727,16,31,9,3,31,10,3,31,7,1,...,0,0,0,0,0,0,0,0,0,8
755,17,9,4,1,2,2,1,0,0,0,...,0,0,0,0,0,0,0,0,0,15
758,18,31,13,2,31,16,3,31,13,2,...,31,31,31,31,31,31,31,31,31,8
780,19,5,5,5,5,5,5,5,5,5,...,0,0,0,0,0,0,0,0,0,7
789,20,29,29,29,29,29,29,29,29,29,...,26,7,4,26,6,4,29,6,2,8
861,21,31,21,18,31,18,16,31,12,11,...,31,10,4,31,11,4,31,9,3,8
876,22,31,9,1,31,8,0,31,10,0,...,1,0,0,4,0,0,8,3,0,15
892,23,31,2,1,31,2,1,31,2,2,...,31,28,15,31,30,18,31,30,25,7
910,24,23,7,0,25,8,0,25,10,0,...,0,0,0,0,0,0,0,0,0,7
931,25,0,0,0,0,0,0,0,0,0,...,31,11,1,31,10,1,31,11,1,8
957,26,31,6,1,31,10,2,31,9,2,...,20,15,12,18,14,11,15,13,11,10
973,27,31,30,28,31,30,30,31,31,31,...,31,12,1,30,16,1,30,15,0,15
1001,28,31,11,4,31,12,4,31,10,3,...,30,10,1,28,11,1,22,9,0,7
1091,29,3,3,1,3,3,1,3,3,1,...,0,0,0,0,0,0,0,0,0,15
1099,30,0,0,0,0,0,0,0,0,0,...,31,5,1,28,5,1,21,4,1,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8109200,11776939,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,15
9380880,11776940,0,0,0,0,0,0,0,0,0,...,31,6,1,28,8,2,21,6,2,15
4245752,11776941,30,30,30,30,30,30,31,31,31,...,31,14,1,31,12,1,31,12,5,7
11188440,11776942,16,7,2,9,6,2,3,3,2,...,2,2,1,2,2,1,2,2,1,8
6563934,11776943,31,31,31,31,31,31,31,31,31,...,31,16,9,31,19,15,31,24,22,15
9218634,11776944,30,6,3,26,5,1,24,4,1,...,26,5,1,24,4,1,24,5,1,10
8816901,11776945,31,5,0,31,4,0,31,5,1,...,31,31,31,31,27,27,31,21,20,15
10474288,11776946,31,5,1,31,7,2,31,9,3,...,31,31,31,31,31,31,31,31,31,1
3367641,11776947,0,0,0,0,0,0,0,0,0,...,7,5,1,13,10,1,20,16,4,15
6071794,11776948,15,7,0,8,6,0,2,2,0,...,31,0,0,31,0,0,31,0,0,15
5917669,11776949,26,12,7,31,13,7,31,12,7,...,26,9,2,20,7,2,16,6,2,15
11776967,11776950,8,2,0,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,15
10166535,11776951,3,3,3,10,8,8,15,13,13,...,12,5,0,12,5,0,5,2,0,8
10572759,11776952,31,3,3,31,3,3,31,4,3,...,26,23,17,31,29,22,31,30,25,8
637065,11776953,30,5,0,30,6,0,30,6,0,...,31,30,24,28,28,23,21,21,16,15
5843119,11776954,31,2,0,31,5,0,31,5,0,...,31,4,1,31,5,1,31,8,3,8
3448167,11776955,31,2,0,31,2,0,31,2,0,...,4,4,2,0,0,0,0,0,0,15
1357412,11776956,30,30,3,30,30,3,31,31,3,...,0,0,0,0,0,0,5,4,1,15
8013694,11776957,9,1,0,16,5,0,22,9,0,...,31,31,31,31,31,31,31,31,31,7
3005810,11776958,31,15,4,31,18,10,31,21,14,...,0,0,0,0,0,0,0,0,0,7
4249969,11776959,31,3,0,31,3,0,31,2,0,...,31,1,0,31,2,0,31,2,0,15
8607974,11776960,16,11,8,15,11,8,9,9,8,...,31,31,29,31,31,29,31,31,29,15
11223634,11776961,31,6,0,31,5,0,31,7,0,...,31,17,0,30,15,0,29,16,0,7
10238012,11776962,31,11,10,31,14,12,31,16,14,...,30,16,8,30,18,11,30,22,12,8
10596275,11776963,0,0,0,0,0,0,0,0,0,...,9,9,1,15,15,1,22,22,1,7
8107134,11776964,31,10,0,31,7,0,31,8,0,...,31,6,0,31,7,0,31,8,0,7
3328830,11776965,12,10,7,19,13,7,25,19,13,...,31,16,1,31,18,1,31,19,2,15
5771868,11776966,31,2,0,31,5,0,31,6,0,...,0,0,0,0,0,0,0,0,0,15
5208860,11776967,31,31,31,31,31,31,31,31,30,...,27,2,0,31,2,0,31,3,0,15
3243102,11776968,0,0,0,0,0,0,4,3,0,...,31,31,0,31,31,0,31,31,0,15

In [0]:
test_new.to_csv(path+'/mod_test.csv', index=False)

In [0]:
test=test.merge(features1,on="node1_id")

In [0]:
test=test.merge(features2,on="node2_id")

In [0]:
test.drop(['node1_id', 'node2_id'], axis=1)

,id,f1_x,f2_x,f3_x,f4_x,f5_x,f6_x,f7_x,f8_x,f9_x,...,f4_y,f5_y,f6_y,f7_y,f8_y,f9_y,f10_y,f11_y,f12_y,f13_y
0,1,31,6,1,31,6,1,31,8,1,...,31,24,3,31,25,3,31,26,4,15
1,6056943,0,0,0,0,0,0,0,0,0,...,31,24,3,31,25,3,31,26,4,15
2,3434399,31,19,0,31,18,0,31,19,0,...,31,24,3,31,25,3,31,26,4,15
3,3699049,31,30,0,31,30,2,31,30,2,...,31,24,3,31,25,3,31,26,4,15
4,4448588,20,0,0,27,0,0,31,0,0,...,31,24,3,31,25,3,31,26,4,15
5,1514667,31,6,1,31,6,1,31,8,1,...,5,5,1,5,5,1,0,0,0,15
6,5262085,31,6,1,31,6,1,31,8,1,...,31,26,5,31,28,4,31,29,3,15
7,11329532,31,0,0,31,0,0,31,1,0,...,31,26,5,31,28,4,31,29,3,15
8,10094767,31,6,1,31,6,1,31,8,1,...,31,11,0,31,10,0,31,8,0,15
9,2807701,31,31,31,31,31,31,31,31,31,...,31,11,0,31,10,0,31,8,0,15
10,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,7
11,318497,11,8,3,4,3,2,0,0,0,...,0,0,0,0,0,0,0,0,0,7
12,1443735,30,0,0,31,0,0,31,0,0,...,0,0,0,0,0,0,0,0,0,7
13,6959,0,0,0,0,0,0,0,0,0,...,13,3,0,13,3,0,8,2,0,7
14,1563179,0,0,0,0,0,0,0,0,0,...,31,10,0,31,16,0,31,20,1,7
15,4717168,0,0,0,0,0,0,0,0,0,...,31,10,0,31,16,0,31,20,1,7
16,6778759,29,5,1,29,3,0,29,3,0,...,31,10,0,31,16,0,31,20,1,7
17,3685651,9,8,8,13,12,12,13,12,12,...,31,10,0,31,16,0,31,20,1,7
18,1860966,0,0,0,0,0,0,0,0,0,...,1,1,0,1,1,0,1,1,0,15
19,2360328,0,0,0,0,0,0,0,0,0,...,31,17,0,31,17,0,31,16,0,7
20,7861317,31,7,1,31,9,1,31,9,1,...,31,17,0,31,17,0,31,16,0,7
21,4889367,30,1,0,30,4,1,30,4,1,...,31,17,0,31,17,0,31,16,0,7
22,2474198,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,7
23,5435005,26,2,0,25,2,0,26,4,0,...,0,0,0,0,0,0,0,0,0,7
24,3374548,4,0,0,8,1,0,8,1,0,...,0,0,0,0,0,0,0,0,0,7
25,1576832,0,0,0,0,0,0,3,3,1,...,0,0,0,0,0,0,0,0,0,7
26,2780418,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,6,0,0,7
27,9526298,31,14,0,31,16,0,31,19,1,...,0,0,0,0,0,0,6,0,0,7
28,3234648,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,2,0,0,15
29,3760883,31,31,30,31,31,30,31,31,30,...,0,0,0,0,0,0,2,0,0,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11776938,11775044,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,15
11776939,11775074,17,3,0,19,4,1,19,4,1,...,25,25,23,26,26,26,22,22,21,8
11776940,11775111,0,0,0,1,1,0,1,1,0,...,0,0,0,0,0,0,0,0,0,15
11776941,11775181,28,4,2,21,2,1,15,2,1,...,2,2,0,1,1,0,0,0,0,15
11776942,11775300,31,31,31,31,31,31,31,31,31,...,27,4,1,31,4,1,31,4,1,10
11776943,11775357,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,1,1,15
11776944,11775477,1,1,0,1,1,0,1,1,0,...,1,1,0,1,1,0,1,1,0,15
11776945,11775569,3,3,3,2,2,2,2,1,1,...,0,0,0,0,0,0,0,0,0,15
11776946,11775592,29,7,6,31,8,6,31,8,7,...,0,0,0,0,0,0,0,0,0,15
11776947,11775598,31,1,0,31,2,0,31,3,0,...,11,7,1,5,5,1,1,1,0,15
11776948,11775682,1,1,0,1,1,0,1,1,0,...,31,8,2,31,8,2,31,10,2,15
11776949,11775721,31,31,23,31,31,20,31,31,19,...,31,31,19,31,31,16,31,31,21,15
11776950,11775761,0,0,0,0,0,0,0,0,0,...,31,1,0,31,1,0,31,1,0,15
11776951,11775837,0,0,0,0,0,0,0,0,0,...,26,0,0,26,0,0,26,0,0,15
11776952,11775881,31,15,0,31,15,0,31,13,0,...,30,29,0,30,28,0,31,30,0,15
11776953,11776000,31,2,2,31,6,5,31,9,6,...,3,0,0,9,1,0,16,1,0,15
11776954,11776011,31,2,1,31,2,1,31,3,1,...,31,15,0,31,14,0,31,13,0,7
11776955,11776034,18,7,4,25,13,10,31,14,10,...,31,1,0,31,1,0,31,0,0,15
11776956,11776051,0,0,0,0,0,0,0,0,0,...,31,1,0,31,2,0,31,4,0,1
11776957,11776298,31,14,1,31,17,1,31,20,1,...,31,1,0,31,1,0,31,1,0,15
11776958,11776325,31,13,0,31,14,0,31,16,0,...,0,0,0,0,0,0,0,0,0,15
11776959,11776358,31,1,0,31,2,0,31,2,0,...,31,5,2,31,5,2,31,11,4,8
11776960,11776414,31,2,0,31,4,0,31,8,0,...,31,6,1,31,6,1,31,6,1,8
11776961,11776446,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,15
11776962,11776669,22,1,0,16,1,0,10,1,0,...,0,0,0,0,0,0,0,0,0,7
11776963,11776675,31,0,0,31,0,0,31,0,0,...,31,22,8,31,22,8,31,21,10,7
11776964,11776763,18,18,18,13,13,13,7,7,7,...,13,13,13,7,7,7,0,0,0,15
11776965,11776771,16,5,4,12,0,0,11,0,0,...,31,8,2,31,7,1,31,11,1,15
11776966,11776890,31,6,0,31,8,0,31,12,0,...,5,1,0,0,0,0,3,0,0,15
11776967,11776950,8,2,0,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,15

In [0]:
test.to_csv(path+'/mod_test.csv', index=False)

In [0]:
dep_var = 'is_chat'
cat_names = ['f1_x','f2_x','f3_x','f4_x','f5_x','f6_x','f7_x','f8_x','f9_x','f10_x','f11_x','f12_x','f13_x','f1_y','f2_y','f3_y','f4_y','f5_y','f6_y','f7_y','f8_y','f9_y','f10_y','f11_y','f12_y','f13_y']
#cont_names = ['age', 'fnlwgt', 'education-num']
procs = [FillMissing, Categorify, Normalize]

In [0]:
test = TabularList.from_df(test_new ,path=path, cat_names=cat_names,procs=procs)

In [0]:
data = (TabularList.from_df(df, cat_names=cat_names,  procs=procs)
                           .split_by_idx(list(range(40000,80000)))
                           .label_from_df(cols=dep_var)
                           .add_test(test)
                           .databunch())

In [0]:
data.show_batch(rows=5)

In [0]:
learn = tabular_learner(data, layers=[200,100], metrics=accuracy)

In [0]:
learn.fit(1, 1e-2)

In [0]:
learn.save('hike2')

In [0]:
learn.export(path+"/export2.pkl")

In [0]:
help(load_learner)

Help on function load_learner in module fastai.basic_train:

load_learner(path:Union[pathlib.Path, str], file:Union[pathlib.Path, str, _io.BufferedWriter, _io.BytesIO]='export.pkl', test:fastai.data_block.ItemList=None, **db_kwargs)
    Load a `Learner` object saved with `export_state` in `path/file` with empty data, optionally add `test` and load on `cpu`. `file` can be file-like (file or buffer)

In [0]:
learn = load_learner(path,'export2.pkl',test=test)

In [0]:
preds,target= learn.get_preds(ds_type=DatasetType.Test)

In [0]:
target

tensor([0, 0, 0,  ..., 0, 0, 0])

In [0]:
help(learn.get_preds)

Help on method get_preds in module fastai.basic_train:

get_preds(ds_type:fastai.basic_data.DatasetType=<DatasetType.Valid: 2>, with_loss:bool=False, n_batch:Union[int, NoneType]=None, pbar:Union[fastprogress.fastprogress.MasterBar, fastprogress.fastprogress.ProgressBar, NoneType]=None) -> List[torch.Tensor] method of fastai.basic_train.Learner instance
    Return predictions and targets on `ds_type` dataset.

In [0]:
id=[]
i=0
for j in range(len(target)):
  i=j+1
  id.append(i)

In [0]:
id[:5]

[1, 2, 3, 4, 5]

In [0]:
df = pd.DataFrame({'id':id, 'is_chat':target}, columns=['id', 'is_chat'])

In [0]:
df.to_csv(path+'/submission3.csv', index=False)

In [0]:
len(test)

11776968